serverPort: 9998
persistence:
  enabled: false
# replicas: 1
# storageLocation:
# compactionIntervalSeconds:
cluster:
  clusterId: 1
  multiMaster: false
  knownHosts:
    - hostname: localhost
      port: 9998
    - hostname: localhost
      port: 9997
    - hostname: localhost
      port: 9996