serverPort: 9998
persistence:
  enabled: false
cluster:
  clusterSize: 3
  multiMaster: false
  discoveryMethod:
    knownHosts:
      - hostname: localhost
        port: 9998
      - hostname: localhost
        port: 9997
      - hostname: localhost
        port: 9996